import "./globals.css";
import NavMenu from "./NavMenu";
import AuthProvider from "./AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <NavMenu />
          <main>{children}</main>
        </body>
      </html>
    </AuthProvider>
  );
}
